name: intuosol_design_system
description: "A Flutter design system package that provides IntuoSol's brand-consistent UI components, theming with Oxanium font, and logos."
version: 0.1.0
homepage: https://intuosol.com
repository: https://github.com/intuosol/intuosol_design_system
issue_tracker: https://github.com/intuosol/intuosol_design_system/issues

topics:
  - design-system
  - branding
  - theme
  - logo
  - typography

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/logos/
